# OS ---------------------------------------------------------------------------
os: linux

# meta -------------------------------------------------------------------------
language: r
cache: packages
latex: false
branches:
  only:
  - master

# Stages -----------------------------------------------------------------------

install: true
script:
  - Rscript -e 'if (!requireNamespace("lintr")) install.packages("lintr")'
  - Rscript -e 'if (!requireNamespace("remotes")) install.packages("remotes")'
  - Rscript -e 'remotes::install_deps()'
  - R CMD build --no-build-vignettes .
  - R CMD INSTALL *.tar.gz
  - Rscript -e 'lintr::lint_package()'

addons:
  apt:
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
