# fs::dir_create("paper/figs")
knitr::purl(input = "paper/paper.Rmd", output = "paper/code.R", quiet = TRUE)
source("paper/code.R", chdir = TRUE)
# knitr::spin("paper/code.R")
# fs::file_move("code.md", "paper/code.md")
# fs::file_delete(c("code.md", "paper/code.R", "code.html"))
